# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [1]:
import json

# Use this cell for your code
import numpy as np
N = int(1e7)
A = np.arange(0,N,1)
B = np.arange(0,N,1)

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [2]:
def add_with_for(A,B):
    C = np.empty(N,dtype=int)
    for i in range(N):
        C[i] = A[i] + B[i]
    return C

C = add_with_for(A,B)
print(C[:3])

[0 2 4]


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [3]:
# Use this cell for your code
C = A+B
print(C[:3])

#only 42ms,much faster than above 4s

[0 2 4]


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [4]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
# Use this cell for your code
a = np.arange(100)
a = a.reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [6]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [7]:
# Use this cell for your code
b = a % 2
b = b.astype(float)
print(b)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


3. Create the following array (D):

In [8]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [9]:
# Use this cell for your code
D = np.ones((10,10),dtype=float)
np.fill_diagonal(D,0)
print(D)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [10]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
# Use this cell for your code
E = np.ones((10,10),dtype=float)
i,j = np.indices((10,10))
E[i+j == 9] = 0
print(E)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [12]:
# Use this cell for your code
DE = np.dot(D,E)
D_E = np.linalg.det(D) * np.linalg.det(E)

print(np.linalg.det(DE))

print(D_E)

-81.0000000000001
-81.0


-- *Use this markdown cell for your written answer* --

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [13]:
# Use this cell for your code
from sklearn.datasets import fetch_california_housing
import numpy as np

# 加载数据
c = fetch_california_housing()

matrix = c.data
print(matrix.shape)

(20640, 8)


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [14]:
# Use this cell for your code
print(c.feature_names)

rows = np.where(matrix[:,3] > 2)[0]
print(rows[0:3])

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
[ 710 1023 1024]


3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [15]:
# Use this cell for your code
rows = np.where((matrix[:,1] >= 1) & (matrix[:,1] <= 3))[0]
print(len(rows))


124


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [16]:
# Use this cell for your code
print(c.target)
rows = np.where(c.target > 0.25)[0]
mean = np.mean(matrix[rows,4])
print(mean)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]
1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [17]:
# Use this cell for your code
import json
address = r"C:\Users\Lenovo\Desktop\Helsinki University\Period1\Introduction to Data Science\Homework\Week1\Automotive_5.json"

with open(address,"r") as f:
    data = [json.loads(line) for line in f]

print(data[0].keys())

dict_keys(['overall', 'verified', 'reviewTime', 'reviewerID', 'asin', 'style', 'reviewerName', 'reviewText', 'summary', 'unixReviewTime'])


In [18]:
print(data[0]['reviewText'])

After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  Then the charge / sync cable goes through the hole and you can charge from the side.  When used in landscape position this stand does make more sense so I'm upgrading this review from 2 stars to 4 stars (which I rarely do, but in this case user error) with a star off for lack of documentation.  Manufacturer has said he will include directions and I would also encourage him to update the photos on Amazon with more examples of how this can be used.  The wood quality is indeed good and it's a sturdy little stand.  I'm trying to think of when I'd actually use this stand... perhaps for Facetime chats.  I also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [19]:
# Use this cell for your code
def process(text):
    return text.lower()

for doc in data:
    if 'reviewText' in doc:
        doc['reviewText'] = process(doc['reviewText'])
    else:
        doc['reviewText'] = ""

print(data[0]['reviewText'])

after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [20]:
# Use this cell for your code
import string
address = r"C:\Users\Lenovo\Desktop\Helsinki University\Period1\Introduction to Data Science\Homework\Week1\stopwords-en.txt"
with open(address,"r") as f:
    stopwords = set(f.read().split())

def process2(text):
    if text is None:
        return ""
    text = text.translate(str.maketrans("", "", string.punctuation))
    words = text.split()
    words = [w for w in words if w not in stopwords]
    return " ".join(words)

for doc in data:
    if 'reviewText' in doc:
        doc['reviewText'] = process2(doc['reviewText'])
    else:
        doc['reviewText'] = ""

print(data[0]['reviewText'])

wrote review manufacturer contacted explained use instead current picture amazon phone placed vertically actually use stand phone placed horizontally charge sync cable goes hole charge used landscape position stand does make sense im upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer said include directions encourage update photos amazon examples used wood quality good sturdy little stand im trying think id actually use stand facetime chats think useful open office environment want phone desk alerts notifications easily hope updated review helps original review throwing stand garbage crafted nice wood functional near tell does come instructions product description confusing english poorly translated chinese iphone sits stand just fine stand way plug plug stand blocks turn iphone plug just looks strange im sure hole stand supposed included plastic feet instructions affixed stand began wobble figure work thing post review far im concerned box exp

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [21]:
# Use this cell for your code
from nltk.stem import PorterStemmer
def process3(text):
    if text is None:
        return ""
    words = text.split()
    words = [PorterStemmer().stem(w) for w in words]
    return " ".join(words)

for doc in data:
    if 'reviewText' in doc:
        doc['reviewText'] = process3(doc['reviewText'])
    else:
        doc['reviewText'] = ""

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [22]:
# Use this cell for your code
with open(r"C:\Users\Lenovo\Desktop\Helsinki University\Period1\Introduction to Data Science\Homework\Week1\pos.txt", "w") as pos_file, \
     open(r"C:\Users\Lenovo\Desktop\Helsinki University\Period1\Introduction to Data Science\Homework\Week1\neg.txt", "w") as neg_file:

    for doc in data:
        rating = doc.get('overall', 3)
        review = doc.get('reviewText', "").strip()
        if rating in [4, 5]:
            if review:
                pos_file.write(review + "\n")
        elif rating in [1, 2]:
            if review:
                neg_file.write(review + "\n")

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

In [ ]:
# sqlite> .schema Employees
# CREATE TABLE [Employees]
# (      [EmployeeID] INTEGER PRIMARY KEY AUTOINCREMENT,
#        [LastName] TEXT,
#        [FirstName] TEXT,
#        [Title] TEXT,
#        [TitleOfCourtesy] TEXT,
#        [BirthDate] DATE,
#        [HireDate] DATE,
#        [Address] TEXT,
#        [City] TEXT,
#        [Region] TEXT,
#        [PostalCode] TEXT,
#        [Country] TEXT,
#        [HomePhone] TEXT,
#        [Extension] TEXT,
#        [ReportsTo] INTEGER,
#            FOREIGN KEY ([ReportsTo]) REFERENCES [Employees] ([EmployeeID])
#                 ON DELETE NO ACTION ON UPDATE NO ACTION
# );

In [ ]:
#List the first name, last name, and hire date of all employees hired after January 1st, 1994.

#Answer:
sqlite> select FirstName, LastName,HireDate from Employees where HireDate >= "1994-01-01";


# Robert|King|1994-01-02
# Laura|Callahan|1994-03-05
# Anne|Dodsworth|1994-11-15

In [ ]:
#Count how many orders each customer has placed.
sqlite> select c.CustomerID,c.ContactName,count(o.OrderID) as cnt from Customers c join Orders o on c.CustomerID = o.CustomerID group by c.CustomerID;
# ALFKI|Maria Anders|6
# ANATR|Ana Trujillo|4
# ANTON|Antonio Moreno|7
# AROUT|Thomas Hardy|13
# BERGS|Christina Berglund|18
# BLAUS|Hanna Moos|7
# BLONP|Frédérique Citeaux|11
# BOLID|Martín Sommer|3
# BONAP|Laurence Lebihan|17
# BOTTM|Elizabeth Lincoln|14
# BSBEV|Victoria Ashworth|10
# CACTU|Patricio Simpson|6
# CENTC|Francisco Chang|1
# CHOPS|Yang Wang|8
# COMMI|Pedro Afonso|5
# CONSH|Elizabeth Brown|3
# DRACD|Sven Ottlieb|6
# DUMON|Janine Labrune|4
# EASTC|Ann Devon|8
# ERNSH|Roland Mendel|30
# FAMIA|Aria Cruz|7
# FOLIG|Martine Rancé|5
# FOLKO|Maria Larsson|19
# FRANK|Peter Franken|15
# FRANR|Carine Schmitt|3
# FRANS|Paolo Accorti|6
# FURIB|Lino Rodriguez|8
# GALED|Eduardo Saavedra|5
# GODOS|José Pedro Freyre|10
# GOURL|André Fonseca|9
# GREAL|Howard Snyder|11
# GROSR|Manuel Pereira|2
# HANAR|Mario Pontes|14
# HILAA|Carlos Hernández|18
# HUNGC|Yoshi Latimer|5
# HUNGO|Patricia McKenna|19
# ISLAT|Helen Bennett|10
# KOENE|Philip Cramer|14
# LACOR|Daniel Tonini|4
# LAMAI|Annette Roulet|14
# LAUGB|Yoshi Tannamuri|3
# LAZYK|John Steel|2
# LEHMS|Renate Messner|15
# LETSS|Jaime Yorres|4
# LILAS|Carlos González|14
# LINOD|Felipe Izquierdo|12
# LONEP|Fran Wilson|8
# MAGAA|Giovanni Rovelli|10
# MAISD|Catherine Dewey|7
# MEREP|Jean Fresnière|13
# MORGK|Alexander Feuer|5
# NORTS|Simon Crowther|3
# OCEAN|Yvonne Moncada|5
# OLDWO|Rene Phillips|10
# OTTIK|Henriette Pfalzheim|10
# PERIC|Guillermo Fernández|6
# PICCO|Georg Pipps|10
# PRINI|Isabel de Castro|5
# QUEDE|Bernardo Batista|9
# QUEEN|Lúcia Carvalho|13
# QUICK|Horst Kloss|28
# RANCH|Sergio Gutiérrez|5
# RATTC|Paula Wilson|18
# REGGC|Maurizio Moroni|12
# RICAR|Janete Limeira|11
# RICSU|Michael Holz|10
# ROMEY|Alejandra Camino|5
# SANTG|Jonas Bergulfsen|6
# SAVEA|Jose Pavarotti|31
# SEVES|Hari Kumar|9
# SIMOB|Jytte Petersen|7
# SPECD|Dominique Perrier|4
# SPLIR|Art Braunschweiger|9
# SUPRD|Pascale Cartrain|12
# THEBI|Liz Nixon|4
# THECR|Liu Wong|3
# TOMSP|Karin Josephs|6
# TORTU|Miguel Angel Paolino|10
# TRADH|Anabela Domingues|6
# TRAIH|Helvetius Nagy|3
# VAFFE|Palle Ibsen|11
# VICTE|Mary Saveley|10
# VINET|Paul Henriot|5
# WANDK|Rita Müller|10
# WARTH|Pirkko Koskitalo|15
# WELLI|Paula Parente|9
# WHITC|Karl Jablonski|14
# WILMK|Matti Karttunen|7
# WOLZA|Zbyszek Piestrzeniewicz|7


In [ ]:
#Find the names of all customers who have ordered the product "Chai".

sqlite> select distinct c.ContactName from Customers c
   ...> join Orders o on c.CustomerID = o.CustomerID
   ...> join OrderDetails od on o.OrderID = od.OrderID
   ...> join Products p on od.ProductID = p.ProductID
   ...> where p.ProductName = "Chai";
# Horst Kloss
# Paula Wilson
# Fran Wilson
# Rita Müller
# Guillermo Fernández
# Yang Wang
# Lúcia Carvalho
# Annette Roulet
# Isabel de Castro
# Renate Messner
# Pirkko Koskitalo
# Miguel Angel Paolino
# Jean Fresnière
# Janine Labrune
# Zbyszek Piestrzeniewicz
# Frédérique Citeaux
# Patricia McKenna
# Christina Berglund
# Jose Pavarotti
# Felipe Izquierdo
# Simon Crowther
# Carlos Hernández
# Hari Kumar
# Paula Parente
# José Pedro Freyre
# Elizabeth Lincoln
# Liu Wong
# Matti Karttunen
# Howard Snyder
# Pascale Cartrain
# Ann Devon

In [ ]:
#Find all orders that have been placed but not yet shipped.

sqlite> select * from Orders where ShippedDate is NULL;
# 11008|ERNSH|7|1998-04-08 00:00:00.000|1998-05-06 00:00:00.000||3|79.46
# 11019|RANCH|6|1998-04-13 00:00:00.000|1998-05-11 00:00:00.000||3|3.17
# 11039|LINOD|1|1998-04-21 00:00:00.000|1998-05-19 00:00:00.000||2|65
# 11040|GREAL|4|1998-04-22 00:00:00.000|1998-05-20 00:00:00.000||3|18.84
# 11045|BOTTM|6|1998-04-23 00:00:00.000|1998-05-21 00:00:00.000||2|70.58
# 11051|LAMAI|7|1998-04-27 00:00:00.000|1998-05-25 00:00:00.000||3|2.79
# 11054|CACTU|8|1998-04-28 00:00:00.000|1998-05-26 00:00:00.000||1|0.33
# 11058|BLAUS|9|1998-04-29 00:00:00.000|1998-05-27 00:00:00.000||3|31.14
# 11059|RICAR|2|1998-04-29 00:00:00.000|1998-06-10 00:00:00.000||2|85.8
# 11061|GREAL|4|1998-04-30 00:00:00.000|1998-06-11 00:00:00.000||3|14.01
# 11062|REGGC|4|1998-04-30 00:00:00.000|1998-05-28 00:00:00.000||2|29.93
# 11065|LILAS|8|1998-05-01 00:00:00.000|1998-05-29 00:00:00.000||1|12.91
# 11068|QUEEN|8|1998-05-04 00:00:00.000|1998-06-01 00:00:00.000||2|81.75
# 11070|LEHMS|2|1998-05-05 00:00:00.000|1998-06-02 00:00:00.000||1|136
# 11071|LILAS|1|1998-05-05 00:00:00.000|1998-06-02 00:00:00.000||1|0.93
# 11072|ERNSH|4|1998-05-05 00:00:00.000|1998-06-02 00:00:00.000||2|258.64
# 11073|PERIC|2|1998-05-05 00:00:00.000|1998-06-02 00:00:00.000||2|24.95
# 11074|SIMOB|7|1998-05-06 00:00:00.000|1998-06-03 00:00:00.000||2|18.44
# 11075|RICSU|8|1998-05-06 00:00:00.000|1998-06-03 00:00:00.000||2|6.19
# 11076|BONAP|4|1998-05-06 00:00:00.000|1998-06-03 00:00:00.000||2|38.28
# 11077|RATTC|1|1998-05-06 00:00:00.000|1998-06-03 00:00:00.000||2|8.53

In [ ]:
#Find the customer who has placed the most orders.
sqlite> select * from Customers c
   ...> join Orders o on c.CustomerID = o.CustomerID
   ...> group by c.CustomerID
   ...> order by count(o.OrderID) DESC limit 1;
# SAVEA|Save-a-lot Markets|Jose Pavarotti|Sales Representative|187 Suffolk Ln.|Boise|ID|83720|USA|(208) 555-8097||10324|SAVEA|9|1996-10-08 00:00:00.000|1996-11-05 00:00:00.000|1996-10-10 00:00:00.000|1|214.27

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**